### ISSUE TITLE
🎨 [App Layout] Create a responsive website header

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#1]
#  Create the website header
---

#### Note: This issue is dependent on #3, please complete that before you continue.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a header I can use to navigate the website.

### Description

Your task is to add the website header as described below.

The content of this header will include:

```
1. "Elewa group" logo on the left
2. A transparent background 
3. White text
```

Logo Url -> https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690297/elewa-group-website/Icons/SVG/_Logo/Logo_White_arvoyx.svg

The header needs to be absolute and of higher z-index so that it appears on top of the page banner.

The header needs to appear as shown below on web and mobile:

<img width="1150" alt="Screenshot 2023-02-02 at 10 57 14" src="https://user-images.githubusercontent.com/29625264/216265120-a57da24a-3076-4897-bd83-67abae3e6a80.png">

<img width="323" alt="Screenshot 2023-02-02 at 11 06 54" src="https://user-images.githubusercontent.com/29625264/216271435-9c79db30-7b58-42a5-9ecf-a166945af71b.png">

### Technical Analysis

Create a layout package in libs/elements/layout

Create a header component inside a components folder of the package above

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.

**Comment by RajabKarume** [comment]
Working on this with [Timothy](https://github.com/timothymureithi)

**Comment by mbuimbogo** [comment]
I'm working on it with [Danstan](https://github.com/Danstan-O)

**Comment by order6677** [comment]
working with Ronaldl[https://github.com/McRonaah] on this

**Comment by McRonaah** [comment]
Working on this with [Awadh](https://github.com/order6677)

**Comment by jobkarani** [comment]
We are working on this with @DMacharia
