### ISSUE TITLE
🎨 [App layout] Create a reusable hero (Top page banner) component for the website (Responsive)

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#10]
# Create a reusable hero (Top page banner) component for the website
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a consistent top page banner for various pages of the website.

### Description
As seen on the designs (link below), there are various pages that share a similar top banner which we'll call the "hero section". The hero section is the first view when a user lands on a page. We need one component that can be reused for every page that needs a top banner.

The contents of the hero will be passed as inputs to the component and will include:

```
1. A subtitle
2. A main tittle
3. An optional footer text
4. A background image link
```

The hero section needs to appear as shown below (but Image and text will vary based on page)

<img width="1232" alt="Screenshot 2023-02-02 at 18 59 51" src="https://user-images.githubusercontent.com/29625264/216375794-4294336b-dcfa-4d17-b3ad-fba0beddd91f.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9
```
### Technical Analysis

This component will be created in libs/elements/layout

The name of the component will be "elewa-hero"

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by IanOdhiambo9** [comment]
# Create a reusable hero (Top page banner) component for the website
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a consistent top page banner for various pages of the website.

### Description
As seen on the designs (link below), there are various pages that share a similar top banner which we'll call the "hero section". The hero section is the first view when a user lands on a page. We need one component that can be reused for every page that needs a top banner.

The contents of the hero will be passed as inputs to the component and will include:

```
1. A subtitle
2. A main tittle
3. An optional footer test
4. A background image link
```

The hero section needs to appear as shown below (but Image and text will vary based on page)

<img width="1232" alt="Screenshot 2023-02-02 at 18 59 51" src="https://user-images.githubusercontent.com/29625264/216375794-4294336b-dcfa-4d17-b3ad-fba0beddd91f.png">


Your assignment is to implement the component to appear as above.

Please take note of all the design features

### Technical Analysis

This component will be created in libs/features/elewa/layout

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. All the functionality still works i.e copy, delete and rendering of the block.

**Comment by Michael-Otieno** [comment]
We are working on this with Festo

**Comment by VinceXIV** [comment]
We'll be doing this. Me and Mildred

**Comment by MildredKoskei** [comment]
@IanOdhiambo9 we would like a review on our pull request.

**Comment by NewtonOmbese** [comment]
Working on this with @mwanasiti

**Comment by jeffoty** [comment]
working on this with @Allan-Ngugi
