### ISSUE TITLE
🎨 ⚡ Button component with animation

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#11]
#  Button component with animation
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable button component that reacts and is animated in a uniform way
I want a good experience on web and phone

### Description
The button has a slider-like look and feel.

Light mode:

<img width="186" alt="image" src="https://user-images.githubusercontent.com/3729474/216372869-31352572-435a-4a07-a2ae-d98d18812c15.png">

Dark mode:

<img width="130" alt="image" src="https://user-images.githubusercontent.com/3729474/216372942-42f07130-9987-4cd8-aa4e-76717b72e607.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
N/A - Design does not change.

### Animation

When hovering over the button, the arrow moves to the left and the text is highlighted.

### Technical Analysis

The button component should be placed in the library **libs/features/components/buttons**
Use the command `nx generate @nrwl/angular:library features/components/buttons` to create this library. Make sure it's a separate commit.

The card is a reusable component that can be used by e.g. the home page to properly display certain components.
The component name is elewa-group-button

The card exposes two Angular inputs, i.e. { "mode": ["light" | "dark"],  "message": [type = text], "action", [type=navigation link] }

The message input determines the text displayed 

The module is named "ButtonsModule" 
It exports the elewa-group-button component, for other modules to import

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component
- [ ] The button has proper animation

**Comment by DaisyOdongo** [comment]
I'm working on this with @Beulah-Matt

**Comment by adamswonder** [comment]
Working on this feature with @JamesMGithire
