### ISSUE TITLE
🎨 Home page impact section

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#12]
#  Create the home "Impact" section
---
**This card depends on:**
- [x] #11
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows an intro the elewa impact
I want a good experience on web and phone

### Description

Design:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/3729474/216375721-9f08b940-4925-4d47-a307-027dbfbbc23f.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the section element.

Re-use components as much as possible
For the buttons, use the `<elewa-group-button></elewa-group-button>` component.

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone

**Comment by jobkarani** [comment]
We are working on this @DMacharia

**Comment by Patrick-Njiru** [comment]
gacheruian

**Comment by timothymureithi** [comment]
Working on this with [Rajab Karume]https://github.com/RajabKarume

**Comment by luckyluvihi** [comment]
working on this

**Comment by JohnstoneDev** [comment]
@Eddahkarambu & I are working on this.

**Comment by malise5** [comment]
I am working on it

**Comment by NewtonOmbese** [comment]
Working on this

**Comment by jeffoty** [comment]
We are working on this with @Allan-Ngugi.

**Comment by IanOdhiambo9** [comment]
Bumped up due to the challenge it has present to the team.
