### ISSUE TITLE
🎨 Home page "Jobs" section

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#13]
#  Create the home page "Jobs" section
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a nice link which captures my attention and sends me to the jobs page
I want a good experience on web and phone

### Description

Design:

<img width="842" alt="image" src="https://user-images.githubusercontent.com/3729474/216376578-22f5fc9c-3c35-400e-b09a-c706261162ca.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the element.

The text "open opportunities" is an anchor link which points to the `/jobs` page

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone

**Comment by EliusCaleb** [comment]
Hey am working on this with Maureen Chepkemoi

**Comment by omaomach** [comment]
Hi, am working on this with @Angie-O

**Comment by Calvin-Ngugi** [comment]
Hey, Ashley and I will be working on this

**Comment by AshleyN2** [comment]
👍🏾 @AshleyN2

**Comment by Kangonga** [comment]
working on this
