### ISSUE TITLE
🎨 [App layout] Website footer

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#15]
#  Create the website footer
---
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)
---

### Summary

As a user I want a simple footer that displays my information in a structured way.
Another component can be injected into the footer to highlight a certain action per page

### Description

Currently the website page has not footer. Your job is to add one.

The footer needs to appear well on web and mobile:

Web:
<img width="858" alt="image" src="https://user-images.githubusercontent.com/3729474/216377655-88858bc9-c879-4959-940b-403fe6b6bd9b.png">

Mobile:
<img width="185" alt="image" src="https://user-images.githubusercontent.com/3729474/216377784-624a463e-6b54-48a6-9d14-323d1d700ca7.png">

---
Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

### Technical Analysis

This feature can be found in apps/elewa-group-website

Create a layout package in libs/elements/layout/footer

Create a footer component inside a components folder of the package above.
Add a module and export the component.

The footer has a dynamic component which can change from page to page, as illustrated below:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/3729474/216378525-d1e3bbbd-2005-446d-8c94-002ca0e884f1.png">

Use simple content projection/transclusion for this through the `<ng-content></ng-content>` element

https://angular.io/guide/content-projection

#### Social media links

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690295/elewa-group-website/Icons/SVG/_Social/instagram_x8ujcq.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/linkedin_x8smhm.svg

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/Icons/SVG/_Social/facebook_lhhwk2.svg

#### company logo

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690297/elewa-group-website/Icons/SVG/_Logo/Logo_White_arvoyx.svg

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone
- [ ] The component allows for a transclusive element that is centered using CSS flex

**Comment by pronepoet** [comment]
Working on this with @[kimuit](https://github.com/kimuit)

**Comment by pauleen123** [comment]
i am now working on this

**Comment by vionaosiako** [comment]
We are working on this with @JG-Mike

**Comment by doreenlulu** [comment]
I am working on this issue with [Martin](https://github.com/codertinie)
