### ISSUE TITLE
🎨 Create reusable team member view (Single team member view) - When clicked

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#16]
#  Create reusable team member view (Single team member view) - When clicked (Responsive)
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a reusable section that shows a team member and some brief info about them

### Description

As seen on the designs (link below), this section contains the following:

```
1. An Image on the left
2. The name and role of the team member
3. Some paragraphs describing the team member
4. A floating button on the image that links to (LinkedIn)
```

The team section needs to appear as shown below.

<img width="1191" alt="Screenshot 2023-02-02 at 19 17 45" src="https://user-images.githubusercontent.com/29625264/216382529-b15e1b3a-7c62-41da-8ef8-4774fd539fff.png">

When the cancel button on the top right corner is clicked the section goes back to view on #41.

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```
### Technical Analysis

This component will be created in  libs/features/components/banners

The component will be called elewa-group-team-member

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by George-Onyango** [comment]
I am working on this
