### ISSUE TITLE
🎨 Home page footer

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#17]
#  Create the home page Footer section
---
**This feature depends on:**
- [x] #11
- [x] #15
- [x] #252
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a nice well-designed footer on the home page
I want a good experience on web and phone

### Description

Design:
<img width="828" alt="image" src="https://user-images.githubusercontent.com/3729474/216379674-bb0f260e-479a-4e83-bf1a-4e96471f16ac.png">

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the element.

Use the elewa-group-footer component. Create a reusable component that acts as CTA for "call to mission":

<img width="792" alt="image" src="https://user-images.githubusercontent.com/3729474/216380249-4ecf002d-0df7-488f-8fc8-ecb20ac94367.png">

On the HomePageComponent, add the footer as follows:

```
<elewa-group-footer>
  <elewa-group-cta-mission></elewa-group-cta-mission>
</elewa-group-footer>
`

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component is clean and does not have more than 30 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone
- [ ] The code reuses other components

**Comment by t-muthuri** [comment]
Working on this with @muriithi-ian

**Comment by mwanasiti** [comment]
We're working on this @Keith Wesley

**Comment by OswaldCc** [comment]
working on this

**Comment by Michael-Otieno** [comment]
working on this

**Comment by Michael-Otieno** [comment]
working on this

**Comment by Michael-Otieno** [comment]
working on this
