### ISSUE TITLE
🎨 Create About us page culture and values section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#18]
#  Create About us page culture and values section
---

#### Note: This feature is dependent on #14, please complete this issue first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the organisations culture and values

### Description

As seen on the designs (link below), this section contains the following:

```
1. A title
2. A section description
3. A grid of culture and values
```

This sections reuses components from #14, use this component to render the values on these section

<img width="1191" alt="Screenshot 2023-02-02 at 19 31 11" src="https://user-images.githubusercontent.com/29625264/216384869-0c3538db-5346-4dde-b705-0505d77bdbc4.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including rounded corners and borders)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```

### Technical Analysis

This component will be created in  libs/pages/elewa/about-us

The component will be called elewa-culture-and-values

icon links:

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Icons/PNG/coorperative_kzlzrg.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Icons/PNG/ownership_yno4a2.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/Holistic_id4kra.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/Education_hstyzo.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/Transparancy_fqal8q.png
### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
5. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
6. The code is isolated to the libs/page/home package, unless a justified reason is specified.
7. The component is aligned using CSS flex
8. The design is responsive for screen, tablet and phone
9. The image renders fast and has multiple srcsets

**Comment by order6677** [comment]
working on this with [Ronald](https://github.com/McRonaah)

**Comment by munenebrian** [comment]
will be trying this issue

**Comment by MiltonChessCoder** [comment]
working on this with @OswaldCc

**Comment by mbuimbogo** [comment]
working on this with [Danstan](https://github.com/Danstan-O)
