### ISSUE TITLE
🎨  Create About us page (We care) section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#19]
#  Create About us page (We care) section
---

#### Note: this issue is dependent on #14, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes our mission and investment as an organisation

### Description

As seen on the designs (link below), this section contains the following:

```
1. A title
2. (2) paragraphs side by side
3. (3) Columns with an icon, title and test vertically aligned
```

The care section needs to appear as shown below (link to icons below)

<img width="1053" alt="Screenshot 2023-02-02 at 19 09 14" src="https://user-images.githubusercontent.com/29625264/216378282-49aa9dbe-e89d-497e-a44d-87b75930daa5.png">

Your assignment is to implement the component to appear as above. The columns below use reusable components from #14. Please take note of that.

Please take note of all the design features (including rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```

#### Icon Links

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Icons/PNG/coorperative_kzlzrg.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/Holistic_id4kra.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Icons/PNG/ownership_yno4a2.png

### Technical Analysis

This component will be created in  libs/pages/elewa/about-us

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
5. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
6. The code is isolated to the libs/page/home package, unless a justified reason is specified.
7. The component is aligned using CSS flex
8. The design is responsive for screen, tablet and phone
9. The image renders fast and has multiple srcsets

**Comment by Michael-Otieno** [comment]
Festo and I are working on this.

**Comment by Michael-Otieno** [comment]
@jrosseel @IanOdhiambo9 awaiting your review of my pull request

**Comment by Michael-Otieno** [comment]
Waiting for review

**Comment by timothymureithi** [comment]
Working on this with [RajabKarume](https://github.com/RajabKarume)

**Comment by McRonaah** [comment]
Working on this with [Awadh](https://github.com/order6677)

**Comment by init-commit** [comment]
Working on this with @jane

**Comment by JG-Mike** [comment]
i am working on this
