### ISSUE TITLE
🎨 About us location section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#20]
#  About us location section
---

#### Note: this feature depends on a component created on #11 

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows the physical location of the organisation and a link to get directions

### Description

As seen on the designs (link below), this section contains the following:

```
1. An interactive map on the right
2. A title
3. A description 
4. A button link
```

The location section needs to appear as shown below including map functionality. When a user clicks the get directions button they should navigate accordingly with ease.

#### Note
Research and propose possible libraries to provide the maps api/service

<img width="1189" alt="Screenshot 2023-02-02 at 19 42 36" src="https://user-images.githubusercontent.com/29625264/216388269-1ae2c257-dab5-4756-a8fc-c655bb9d1500.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```
### Technical Analysis

This component will be created in  libs/pages/elewa/about-us

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by IanOdhiambo9** [comment]
yiu are workin on this

**Comment by adamswonder** [comment]
Creating this feature with @JamesMGithire

**Comment by omaomach** [comment]
I'll be working on this feature.
