### ISSUE TITLE
⌚ Create a reusable TimeLine carousel

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#21]
#  TimeLine carousel
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a carousel that can display a timeline of provided events

### Description

The carousel needs to take in as input a list of events and the number of events to show at a time. The list of events will have objects with the following properties (Create a generic type for this);

```
1. A date
2. A title
3. A description

```

The timeline carousel needs to appear as shown below including navigation functionality. When a user clicks the previous or next button they should navigate accordingly with ease.

<img width="1133" alt="Screenshot 2023-02-02 at 19 54 17" src="https://user-images.githubusercontent.com/29625264/216390044-6043d92b-796e-4be9-a1fe-41556d7ace3d.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```
### Technical Analysis

This component will be created in  features/components/ui-list

The component will be called elewa-horizontal-timeline-carousel

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by anthonymwangi072** [comment]
we are working on with @NEKiarie

**Comment by SirJimKe** [comment]
I will work on this.

**Comment by Calvin-Ngugi** [comment]
We are working on this with @AshleyN2
