### ISSUE TITLE
🎨 Create about us history carousel

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#22]
#  Create about us history carousel
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a carousel that can display a history timeline of the organisation

### Description

In this section the user can track the progress of the organisation throughout the years.

Then section has the following:

1. A title
2. A timeline carousel (reuse #21 )
3. A call to action message

The timeline carousel needs to appear as shown below including navigation functionality. When a user clicks the previous or next button they should navigate accordingly with ease.

<img width="1237" alt="Screenshot 2023-02-02 at 20 10 15" src="https://user-images.githubusercontent.com/29625264/216394180-47d0f86d-f3fd-4591-bbbb-4fc604272947.png">

<img width="1237" alt="Screenshot 2023-02-02 at 20 10 22" src="https://user-images.githubusercontent.com/29625264/216394259-96e456ed-f21d-4096-a249-71cf08485e00.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```
### Technical Analysis

This component will be created in  libs/pages/elewa/about-us

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by 123ZOKzok** [comment]
I am working on this

**Comment by michael-mbugua** [comment]
working on this with @123ZOKzok

**Comment by NEKiarie** [comment]
working on this with @Anthonymwangi072

**Comment by Anna-Ashton** [comment]
working on this with @littlephillips and @chegeian

**Comment by munenebrian** [comment]
working on this
