### ISSUE TITLE
🎨  About us Footer section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#23]
#  About us Footer section
---

#### Note: this feature depends on a component created on #15, please complete this issue first. 

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a footer section on the about us page

### Description

Just add the component on #15 to the bottom of the about page.

<img width="1250" alt="Screenshot 2023-02-02 at 20 14 42" src="https://user-images.githubusercontent.com/29625264/216395097-744fd105-7789-4d3c-9211-b4998e3d89f7.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

mobile 

https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/0efb593f-dc28-4e6d-86f3-098699455ad4
```
### Technical Analysis

This component will be created in  libs/pages/elewa/about-us

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by ndakalajulius** [comment]
I've picked this issue on About us Footer section

**Comment by codertinie** [comment]
I am working on this issue with [Doreen](https://github.com/doreenlulu)

**Comment by mwanasiti** [comment]
worked on this with @newtonombese

**Comment by EliusCaleb** [comment]
working on this
