### ISSUE TITLE
:art: Create Investors page top banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#242]
#  Create Investors page top banner
---

#### Note: this issue is dependent on #10 , please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a top banner page for the Investors page

### Description

As seen on the designs (link below), the section is similar to the page banner component created on #10, reuse that component and pass the relevant data for this section;

The page banner section needs to appear as shown below (link to icons below)

<img width="1218" alt="Screenshot 2023-02-22 at 09 12 23" src="https://user-images.githubusercontent.com/29625264/220537957-8665c5c3-01d8-4341-962c-d3647cf964e0.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690294/elewa-group-website/hero-Images/Investors_qba82u.jpg

### Technical Analysis

This component will be created in  libs/pages/elewa/invest

The componenent will be called elewa-invest-hero

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by NewtonOmbese** [comment]
Working on this

**Comment by lilmithi** [comment]
Working on this
