### ISSUE TITLE
:art: Create Invest Detail Section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#243]
#  Create Invest Detail Section
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a detail section for the investors page.

### Description

The detail section needs to appear as shown below

<img width="1218" alt="Screenshot 2023-02-22 at 09 22 13" src="https://user-images.githubusercontent.com/29625264/220539710-5fd497b5-afbb-4bcf-95c7-694cfb263905.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690306/elewa-group-website/Images/Mask_Group_17_rjkgrq.png

### Technical Analysis

This component will be created in  libs/pages/elewa/invest

The component will be called elewa-invest-detail-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by kimuit** [comment]
Working on it

**Comment by Allan-Ngugi** [comment]
Working on this with @jeffoty.

**Comment by AshleyN2** [comment]
Working on this with @Calvin-Ngugi .
