### ISSUE TITLE
:art: Create Investors Key Figures Section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#245]
#  Create Investors Key Figures Section
---

#### Note: this issue is dependent on #244 , please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows key figures investors need to be aware of on the investors page.

### Description

The card used on this section is similar to one created on the issue #244, please reuse that can create a responsive card grid to appear as shown below.

Key figures should be an array with the key figure string and a description

<img width="1217" alt="Screenshot 2023-02-22 at 09 25 35" src="https://user-images.githubusercontent.com/29625264/220542458-aa5e9919-7307-4b64-8683-48000c32cb39.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c
```

### Technical Analysis

This component will be created in  libs/pages/elewa/invest

The componenent will be called elewa-invest-key-figures-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by munenebrian** [comment]
working on this with @omaomach

**Comment by pauleen123** [comment]
i am working on this

**Comment by kahoragachau** [comment]
Working on this

**Comment by chegeian** [comment]
working on this

**Comment by Bel-94** [comment]
working on this

**Comment by Anna-Ashton** [comment]
Working on this with [@chegeian](https://github.com/chegeian/chegeian)
