### ISSUE TITLE
🎨 Create Invest stakeholder section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#246]
#  🎨 Create Invest stakeholder section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the investors stakeholder section.

### Description

This component displays provided text and images side by side on the stakeholder section..

Then section has the following :

```
1. An image on the left side
2. A paragraph of text (2)
3. A title

```

<img width="1108" alt="Screenshot 2023-02-22 at 09 43 09" src="https://user-images.githubusercontent.com/29625264/220543393-7d2e3f54-2133-4cad-a855-643c00e10c7a.png">

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af
mobile 
-

#### Image link
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690303/elewa-group-website/Images/IMG_6523_vabpyo.png
```
### Technical Analysis

This component will be created in libs/pages/elewa/invest

The component will be called elewa-invest-stakeholder-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by NewtonOmbese** [comment]
Working on this

**Comment by nziokikevin** [comment]
working on this

**Comment by kahoragachau** [comment]
Working on this.
