### ISSUE TITLE
Create Invest creative-hub section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#247]
#  🎨 Create Invest creative-hub section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the investors creative hub section.

### Description

This component displays provided text and images side by side on the creative hub section..

Then section has the following :

```
1. An image on the right side
2. A paragraph of text (2)
3. A title

```
<img width="1108" alt="Screenshot 2023-02-22 at 09 43 17" src="https://user-images.githubusercontent.com/29625264/220544105-d1040eb7-d02a-4eba-bb75-09ecab976174.png">

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af

#### Image link
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690302/elewa-group-website/Images/Mask_Group_20_yshsq2.png
```
### Technical Analysis

This component will be created in libs/pages/elewa/invest

The component will be called elewa-invest-creative-hub-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by pronepoet** [comment]
I am working on this

**Comment by kahoragachau** [comment]
Working on this.

**Comment by omaomach** [comment]
am working on this with @munenebrian
