### ISSUE TITLE
🎨 Create Invest page investing section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#248]
#  🎨 Create Invest page investing section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes how to invest in elewa.

### Description

This component displays provided text and images side by side on the invest in elewa section..

You will need to extend an optional button field (reusable animation button #11 )on the original reusable component, also add an input with the buttonText and url to navigate to. (Needs to utilize a navigate function on the component file)

Then section has the following :

```
1. An image on the left side
2. A paragraph of text (1)
3. A button.
4. A title

```

<img width="1108" alt="Screenshot 2023-02-22 at 09 43 24" src="https://user-images.githubusercontent.com/29625264/220545247-36cb1c76-012d-40b6-8c0e-edaa62392239.png">

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af

#### Image link
```
https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690302/elewa-group-website/Images/f2b2ea6afc31e9720638da1bbd0d2d69_p58coq.png
```
### Technical Analysis

This component will be created in libs/pages/elewa/invest

The component will be called elewa-invest-investing-in-elewa-section

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
5. The code is isolated to the libs/page/home package, unless a justified reason is specified.
6. The component is aligned using CSS flex
7. The design is responsive for screen, tablet and phone
8. The image renders fast and has multiple srcsets

**Comment by Calvin-Ngugi** [comment]
I am working on this with @AshleyN2

**Comment by Kangonga** [comment]
working on this

**Comment by George-Onyango** [comment]
Working on this with @23po

**Comment by NewtonOmbese** [comment]
Working on this
