### ISSUE TITLE
:fire: Make Home Page Jobs Section reusable

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#249]
#  🎨 Make Home Page Jobs Section reusable
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section I can use to display call to action messages with links to the action.

### Description

Currently a component has been implemented on the home-page that enables this feature. Instead of creating a new one, we'll reuse the one already created.

Your task is to create a new reusable component, migrate the code for home-page-jobs-section to this component (html, scss, ts).

Make the home-page-jobs-section reuse this component.

The section has the following Inputs:

```
1. A message (string)
2. A call to action text (the one in bold and underlined on hover) (string)
3. A text align (should only accept - "center", "left", "right", "justified")
4. A url to navigate to (string)

```

Use a function on the component file for navigation.

<img width="1108" alt="Screenshot 2023-02-22 at 09 43 31" src="https://user-images.githubusercontent.com/29625264/220548949-8668d987-9ff0-41d2-8092-32ca97189222.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af
```

### Technical Analysis

Move the reusable component to features/components/banners

The component will be called elewa-call-to-action-banner

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by marcokumu** [comment]
@mwanjiku56 and I are working on this

**Comment by Kangonga** [comment]
working on this

**Comment by EliusCaleb** [comment]
working on this

**Comment by timothymureithi** [comment]
Working on this
