### ISSUE TITLE
🎨 Create social impact page top banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#25]
#  Create social impact page top banner
---

#### Note: this issue is dependent on #10 , please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a top banner page for the social impact page

### Description

As seen on the designs (link below), the section is similar to the page banner component created on #10, reuse that component and pass the relevant data for this section;

The page banner section needs to appear as shown below (link to icons below)

<img width="1250" alt="Screenshot 2023-02-03 at 08 43 40" src="https://user-images.githubusercontent.com/29625264/216522374-0b1027c9-aa19-4324-aa5a-4dcbc018c8bd.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c
```

### Technical Analysis

This component will be created in  libs/pages/elewa/social-impact

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
5. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
6. The code is isolated to the libs/page/home package, unless a justified reason is specified.
7. The component is aligned using CSS flex
8. The design is responsive for screen, tablet and phone
9. The image renders fast and has multiple srcsets

**Comment by Allan-Ngugi** [comment]
We are working on this with @Jeffoty

**Comment by yegobaroni** [comment]
Working on this with @Dx901 and @muriithi-ian.

**Comment by JohnstoneDev** [comment]
@Essyuge & I are working on this.

**Comment by nziokikevin** [comment]
Working on this.

**Comment by codertinie** [comment]
I am working on this with @mercylynn0

**Comment by mwanjiku56** [comment]
working on this with @marcokumu

**Comment by Danstan-O** [comment]
working on this with @mbuimbogo
