### ISSUE TITLE
:art: Create the Invest page call-to-action section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#250]
#  Create the Invest page call-to-action section
---

#### Note: this feature is dependent on #249, Please complete that one first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a nice link which captures my attention and sends me to the invest call to action
I want a good experience on web and phone

### Description

Design:

<img width="1108" alt="Screenshot 2023-02-22 at 09 43 31" src="https://user-images.githubusercontent.com/29625264/220549877-8aafa41b-f241-4f74-820c-f730eff4c230.png">

Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/d601deb2-7100-407e-aed2-6c782b5006af
```

### Technical Analysis

This feature can be found in libs/pages/elewa/invest

The component will be called elewa-invest-call-to-action-section

The text "investing" is an anchor link which points to the `/invest` page

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone

**Comment by init-commit** [comment]
Working on this.

**Comment by Dx901** [comment]
Working on this with @yegobaroni
