### ISSUE TITLE
:fire: Make the footer Dynamic

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#252]
# Make the footer Dynamic
---

#### Note: this feature depends on a component created on #15, please complete this issue first. 

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a footer section on all pages that takes advantage of the transclusion capabilities of the footer section

### Description

The footer has already been created, however, the transclusion bit is not yet fully implemented. Depending on the current active page, the footer transclusion section needs to switch it's component. Since the footer is only added to the main page layout, the switchcase will need to happen there.

For this issue you need to create a swithCase that renders a different component based on the active page (will need to make use of the route), from the route you can get the active page and set a different component everytime the route changes.

All the components in the switchCase will be reusable components.

For more about angular switchase and router see the links below:

https://angular.io/api/common/NgSwitchCase

https://angular.io/api/router

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/grid
-
```
### Technical Analysis

This component will be created in  libs/elements/layout

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by lilmithi** [comment]
Working on this

**Comment by Beulah-Matt** [comment]
@IanOdhiambo9 I have made the requested for changes, see https://github.com/italanta/elewa-group/pull/278
