### ISSUE TITLE
🎨  Create Social Impact people section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#30]
#  Create Social Impact people section
---

#### Note: This issue is dependent on #31, please complete that issue first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a summary in numbers of the organisation impact

### Description

This section contains an auto incrementing figure of the organisation impact, the increment starts from 0 to the provided figure in about 5secs. 

Then section has the following:

```
1. 4 side by side impact figures
2. A description section with an image floated left (reuse component on #31 here).

```

The figure counters need to increment in uniform and with ease

![Screenshot 2023-02-06 at 10 15 23](https://user-images.githubusercontent.com/29625264/216907557-4fc43085-fb53-48f4-9c66-d381fc4f12de.png)

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/pages/elewa/social-impact

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by DaisyOdongo** [comment]
working on this

**Comment by George-Onyango** [comment]
Working on this

**Comment by Calvin-Ngugi** [comment]
I am working on this
