### ISSUE TITLE
🎨 Create reusable text and image banner (side by side)

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#31]
#  Create reusable text and image banner (side by side)
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can reuse throughout the site to display images and text side by side.

### Description

This component displays text and images side by side on the site

Then section has the following as inputs to the component:

```
1. An image url
2. A paragraph of text
3. A title
4. Placement of image ("left" or "right")
5. Background color of the section (Hex Code i.e "#00000")

```

![Screenshot 2023-02-06 at 10 24 37](https://user-images.githubusercontent.com/29625264/216910224-22db5d9e-518b-4642-bbbf-1b8d4fd74702.png)

![Screenshot 2023-02-06 at 10 24 53](https://user-images.githubusercontent.com/29625264/216910240-2c25c186-fb4a-4683-b3f7-eeae0bc5af1d.png)

Your assignment is to implement the component to appear as above.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/features/components/banners

The component will be called elewa-group-image-and-text-banner

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Images/gettyimages-525701055-2048x2048_g7nbt1.png

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by ItotiaHarrison** [comment]
working on this with @mercylynn

**Comment by nicco99** [comment]
we are working on this with @imaculate-echesa

**Comment by imaculate-echesa** [comment]
worked on this.

**Comment by pauleen123** [comment]
we are working on this with @Bel-94

**Comment by Bel-94** [comment]
@IanOdhiambo9 kindly review our pull request. Worked on the issue with @pauleen123

**Comment by Njogu23** [comment]
@IanOdhiambo9 where is is the link to this design?

**Comment by Njogu23** [comment]
I am working on this

**Comment by jeffoty** [comment]
working on this with @Allan-Ngugi

**Comment by Beulah-Matt** [comment]
Working on this.
