### ISSUE TITLE
🎨 [App Layout] Create careers page Module & routing

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#311]
#  Create careers page Module
---

#### Note:

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a careers page that contains the open positions for the organisatiom

### Description

The library to enable this hasn't been created yet. Create the lib and setup routing to it.
You'll need to add a routing file "careers.routing.ts"
You'll need to add the main page for this lib "elewa-careers-page" (inside a pages folder)
Add a careers tab on the header and it's routerLink

Add the elewa-main-page template to the elewa-careers-page

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/a7f37e20-4f02-4b0a-9afc-11c44a0ce560
```

### Technical Analysis

This module will be created in  libs/pages/elewa/careers

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Beulah-Matt** [comment]
Working on this

**Comment by AshleyN2** [comment]
Working on this with @Calvin-Ngugi

**Comment by kahoragachau** [comment]
Working on this.
