### ISSUE TITLE
🎨 Create Careers Why Elewa

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#314]
#  Create Careers Why Elewa
---

#### Note: this issue is dependent on #311, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a career section that shows Elewa's unique value proposition.

### Description

As seen on the designs (link below), this section contains the following:

```
1. 2 images
2. A paragraph
3. A title
```

The care section needs to appear as shown below (link to icons below)

<img width="1305" alt="Screenshot 2023-02-27 at 09 22 43" src="https://user-images.githubusercontent.com/29625264/221489875-31803c97-ee14-41df-b670-88f9d93b9338.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features.

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/a7f37e20-4f02-4b0a-9afc-11c44a0ce560
```

#### Image Links

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690303/elewa-group-website/Images/IMG_6523_vabpyo.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690302/elewa-group-website/Images/CHU-5670_yqvk0y.png

### Technical Analysis

This component will be created in  libs/pages/elewa/careers

The component will be called careers-value-proposition

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by RajabKarume** [comment]
Working on this

**Comment by Eddahkarambu** [comment]
working on this
