### ISSUE TITLE
🎨 Create Contact banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#317]
#  Create Contact banner
---

#### Note: 
Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a contact page banner

### Description

As seen on the designs (link below), this section contains the following:

```
1. A title
2. Contact options
```

The contact section needs to appear as shown below (link to icons below)

<img width="1267" alt="Screenshot 2023-02-27 at 09 41 35" src="https://user-images.githubusercontent.com/29625264/221492811-b78ce7e0-c353-4742-9837-4ac411cf6135.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features.

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/a57c4c47-d3d7-48ce-9b3a-d224a4c624be
```

### Technical Analysis

This component will be created in  libs/pages/elewa/contact

The component will be called contact-banner

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by timothymureithi** [comment]
Working on this

**Comment by order6677** [comment]
working  on this with  [ronald](https://github.com/McRonaah)

**Comment by pauleen123** [comment]
let me work on this
