### ISSUE TITLE
🎨 [App Layout] Create brands page Module

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#318]
#  Create brands page Module
---

#### Note:

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a brands page that contains elewa brands

### Description

The library hasn't been created yet. Create the lib and setup routing to it.
You'll need to add a routing file "brands.routing.ts"
You'll need to add the main page for this lib "elewa-brands-page" (inside a pages folder)
Add a brands tab on the header and it's routerLink

Add the elewa-main-page template to the elewa-brands-page

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/3bb41a81-fd4c-462b-9535-043bc5c55faf
```

### Technical Analysis

This module will be created in  libs/pages/elewa/brands

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Michael-Otieno** [comment]
working on this

**Comment by kahoragachau** [comment]
Working On this

**Comment by Beulah-Matt** [comment]
@IanOdhiambo9 please review my merge request
