### ISSUE TITLE
🎨 Create Social Impact cooperative section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#32]
#  🎨 Create Social Impact cooperative section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the organisation common objectives

### Description

This component displays provided text and images side by side on the social impact section.

Then section has the following :

```
1. An image on the right side
2. A paragraph of text
3. A title

```

![Screenshot 2023-02-06 at 10 24 37](https://user-images.githubusercontent.com/29625264/216910224-22db5d9e-518b-4642-bbbf-1b8d4fd74702.png)

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/pages/elewa/social-impact

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Eddahkarambu** [comment]
@JohnstoneDev and I will work on this.

**Comment by munenebrian** [comment]
will be trying to work on this

**Comment by codertinie** [comment]
I am working on this with @doreenlulu

**Comment by Bel-94** [comment]
Working on this

**Comment by NewtonOmbese** [comment]
Working on this

**Comment by AshleyN2** [comment]
Worked on this with @Calvin-Ngugi.
