### ISSUE TITLE
🎨 Create brands stakeholder section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#320]
#  Create brands stakeholder section
---

#### Note: this issue is dependent on #10 and #318 , please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a stakeholder section for the brands page

### Description

The section needs to appear as shown below (link to icons below)

<img width="1259" alt="Screenshot 2023-02-27 at 09 58 35" src="https://user-images.githubusercontent.com/29625264/221496574-fe73cf58-5b2e-40f3-a533-cedc77d4bd9e.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/3bb41a81-fd4c-462b-9535-043bc5c55faf
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690296/elewa-group-website/Icons/SVG/Brands_hfslt4.svg

### Technical Analysis

This component will be created in  libs/pages/elewa/brands

The component will be called elewa-brands-stakeholder

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by timothymureithi** [comment]
Working on this
