### ISSUE TITLE
🎨 Create reusable brand banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#321]
#  Create reusable brand banner
---

#### Note: this issue is dependent on #10 and #318 , please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a banner I can use to display brands on the brands page.

### Description

The banner takes the following inputs

```
1. Brand Logo
2. Brand Name
3. Brands Description
4. Button Text
5. Button Url (use reusable animated button)
6. Logo Placement ('right' or 'left')

```

The banner needs to appear as shown below

<img width="1126" alt="Screenshot 2023-02-27 at 10 17 03" src="https://user-images.githubusercontent.com/29625264/221498661-64a47538-6068-427e-bb72-201577fb7827.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/3bb41a81-fd4c-462b-9535-043bc5c55faf
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690295/elewa-group-website/Icons/SVG/Elewa_education_pp1gnc.svg

### Technical Analysis

This component will be created in  libs/features/components/banners

The component will be called elewa-brands-banner

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
7. The component is clean and does not have more than 50 lines
8. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
9. The code is isolated to the libs/page/home package, unless a justified reason is specified.
10. The component is aligned using CSS flex
11. The design is responsive for screen, tablet and phone
12. The image renders fast and has multiple srcsets

**Comment by Beulah-Matt** [comment]
Working on this.

**Comment by Dx901** [comment]
Working on this with @Yegobaroni
