### ISSUE TITLE
🎨 Create Venture Labs brand banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#324]
#  Create Venture Labs brand banner
---

#### Note: this issue is dependent on #10, #318 and #321, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a banner I can use to display Venture Labs brand on the brands page.

### Description

The banner has the following

```
1. Brand Logo
2. Brand Name
3. Brands Description
4. Button

```

The banner needs to appear as shown below

<img width="1126" alt="Screenshot 2023-02-27 at 10 21 49" src="https://user-images.githubusercontent.com/29625264/221500733-99b72cc4-d8ac-43b8-9ba4-205ba39400dd.png">

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/3bb41a81-fd4c-462b-9535-043bc5c55faf
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690293/elewa-group-website/Icons/SVG/VentureLabs_i5cq9y.svg

### Technical Analysis

This component will be created in  libs/pages/elewa/brands

The component will be called elewa-brands-venture-labs

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by 23po** [comment]
working on this

**Comment by mwanjiku56** [comment]
working on this.

**Comment by mwanjiku56** [comment]
@IanOdhiambo9 kindly review

**Comment by nziokikevin** [comment]
Working on this.
