### ISSUE TITLE
🎨 Create banner page open opportunities

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#327]
#  Create banner page open opportunities
---

#### Note: This issue reuses the call-to-action-banner in banners module

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a call to action on the brands page.

### Description

Reuse the call-to-action banner

The banner needs to appear as shown below

<img width="1126" alt="Screenshot 2023-02-27 at 10 22 04" src="https://user-images.githubusercontent.com/29625264/221503312-f83fe021-61dc-43ef-a695-ba990c4ae2cd.png">

Please take note of all the design features

#### Link to full design:

```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/3bb41a81-fd4c-462b-9535-043bc5c55faf
```

### Technical Analysis

This component will be created in  libs/pages/elewa/brands

The component will be called elewa-brands-opportunities

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Dcolonel6** [comment]
working on this

**Comment by RajabKarume** [comment]
working on this

**Comment by EliusCaleb** [comment]
Am working on this
