### ISSUE TITLE
🎨 Create Social Impact beyond business section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#33]
#  🎨 Create Social Impact beyond business section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the organisation beyond business.

### Description

This component displays provided text and images side by side on the social impact section.

Then section has the following :

```
1. An image on the left side
2. A paragraph of text
3. A title

```

![Screenshot 2023-02-06 at 10 24 53](https://user-images.githubusercontent.com/29625264/216912201-c3bdc12a-4eb2-418f-be53-d909a73600d3.png)

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

#### Image link

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690301/elewa-group-website/Images/IMG_0764_twyo3k.png
```
### Technical Analysis

This component will be created in libs/pages/elewa/social-impact

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Jane-Wandia** [comment]
im working on this issue on this issue

**Comment by doreenlulu** [comment]
Working on this with [Martin](github.com/codertinie)

**Comment by Bel-94** [comment]
working on this with @pauleen123

**Comment by nicco99** [comment]
I'm working on this

**Comment by RajabKarume** [comment]
I'm working on this with [`Timothy Mureithi`](https://github.com/timothymureithi)

**Comment by pronepoet** [comment]
I am working on this

**Comment by sheilah-ndiema** [comment]
working on this

**Comment by NewtonOmbese** [comment]
Working on this

**Comment by Bel-94** [comment]
working on this

**Comment by Njogu23** [comment]
I am working on this

**Comment by EliusCaleb** [comment]
working on this
