### ISSUE TITLE
 🎨 Create Social Impact open knowledge section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#34]
#  🎨 Create Social Impact open knowledge section
---

#### Note: This issue is dependent on #31, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that describes the organisation open knowledge

### Description

This component displays provided text and images side by side on the social impact section.

Then section has the following :

```
1. An image on the right side
2. A paragraph of text
3. A title

```

![Screenshot 2023-02-06 at 10 52 47](https://user-images.githubusercontent.com/29625264/216915222-7d1783a6-2458-41f5-b11e-89a53cd91e90.png)

Your assignment is to implement the component to appear as above, reuse the component on #31.

Please take note of all the design features (including mobile and rounded corners)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/pages/elewa/social-impact

The component will be called social-impact-open-knowledge

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690302/elewa-group-website/Images/unnamed_1_m3dvll.png

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by OswaldCc** [comment]
working on this

**Comment by kahoragachau** [comment]
Working on this

**Comment by timothymureithi** [comment]
Working on this with @https://github.com/RajabKarume

**Comment by Bel-94** [comment]
working on this with @pauline123
