### ISSUE TITLE
🎨 Create a reusable vertical list for projects, news etc..

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#35]
#  🎨 Create a reusable vertical list for projects, news etc..
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can reuse to display a list of items projects, news etc 

### Description

This component displays a vertical list of items, it takes a list of the following values as input:

```
1. A title
2. A description (limited to max 50 characters)
3. A date

```

![Screenshot 2023-02-06 at 11 04 14](https://user-images.githubusercontent.com/29625264/216917327-0e067dd1-d527-4a37-a3e3-b0824bc5e06f.png)

Your assignment is to implement the component to appear as above

Please take note of all the design features (including mobile)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/features/components/ui-lists

The component will be called elewa-group-vertical-list-one

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by CharlesMuvaka** [comment]
Currently working on this.

**Comment by royokite** [comment]
Working on this.

**Comment by CharlesMuvaka** [comment]
Hey, roy am on that...

**Comment by royokite** [comment]
@CharlesMuvaka Hey, did not see this but I think it's OK since we're allowed three groups per issue. I've made sure to create the PR after you were done as I was done with it as well, so either of them should work.

**Comment by CharlesMuvaka** [comment]
Cool, thanks!

**Comment by IanOdhiambo9** [comment]
Issues are competitive, it's a first come first serve basis..
Whoever completes the issue first gets merged
