### ISSUE TITLE
🎨 Create social impact projects section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#37]
#  🎨  Create social impact projects section
---

#### Note: This issue is dependent on #35 and #38, please complete that issue first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can use to display a list of the organisation projects.

### Description

This component displays the organisation projects.

```
1. A title
2. A list of projects (reuse #35 for this section)
3. A list of organisation partners (resue #38 for this section)
4. A call to action text

```

![Screenshot 2023-02-06 at 11 15 14](https://user-images.githubusercontent.com/29625264/216919333-0121a958-9465-4dd9-820f-4fd4b1b7a2e9.png)

![Screenshot 2023-02-06 at 11 04 14](https://user-images.githubusercontent.com/29625264/216919354-6cd8029e-1621-45da-b76a-4f7c66153b9a.png)

![Screenshot 2023-02-06 at 11 14 32](https://user-images.githubusercontent.com/29625264/216919368-17861a76-4261-42df-834f-93ddbb94f0e3.png)

![Screenshot 2023-02-06 at 11 14 47](https://user-images.githubusercontent.com/29625264/216919386-70157de8-aeac-4f3f-88c5-bb83fe61e314.png)

Your assignment is to implement the component to appear as above, reuse #35 and #38
Please take note of all the design features (including mobile)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
5. The code is isolated to the libs/page/home package, unless a justified reason is specified.
6. The component is aligned using CSS flex
7. The design is responsive for screen, tablet and phone
8. The image renders fast and has multiple srcsets

**Comment by munenebrian** [comment]
working on this

**Comment by Dcolonel6** [comment]
working on this
