### ISSUE TITLE
🎨  Create reusable partner orgs section 

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#38]
#  🎨 Create reusable partner orgs section
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can reuse to display a horizontal list of partners.

### Description

This component displays a horizontal list of partner organisation logos, it takes the following as input:

```
1. A list of imageUrls
```

![Screenshot 2023-02-06 at 11 14 32](https://user-images.githubusercontent.com/29625264/216920259-099126a3-486b-427c-aaf7-f6530821eab5.png)

Your assignment is to implement the component to appear as above

Please take note of all the design features (including mobile)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-

```
### Technical Analysis

This component will be created in libs/features/components/ui-lists

The component will be called elewa-group-horizontal-list-orgs

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
3. The component is clean and does not have more than 50 lines
4. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
5. The code is isolated to the libs/page/home package, unless a justified reason is specified.
6. The component is aligned using CSS flex
7. The design is responsive for screen, tablet and phone
8. The image renders fast and has multiple srcsets

**Comment by philipNgungi037** [comment]
Am working on this with @jasonkiptoo

**Comment by nziokikevin** [comment]
Working on this with @Dcolonel6

**Comment by kahoragachau** [comment]
Working on this @ludwig-murimi

**Comment by SirJimKe** [comment]
Working on this.

**Comment by kahoragachau** [comment]
@IanOdhiambo9 Awaiting feedback and review

**Comment by MiltonChessCoder** [comment]
working on this

**Comment by munenebrian** [comment]
working on this

**Comment by Kangonga** [comment]
Working on this
