### ISSUE TITLE
🎨  Social Impact Footer section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#39]
#  Social Impact Footer section
---

#### Note: this feature depends on a component created on #252, please complete this issue first. 

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a footer section on the social impact page

### Description

Just add the component on #15 to the bottom of the about page.

<img width="1250" alt="Screenshot 2023-02-02 at 20 14 42" src="https://user-images.githubusercontent.com/29625264/216395097-744fd105-7789-4d3c-9211-b4998e3d89f7.png">

Your assignment is to implement the component to appear as above.

Please take note of all the design features 

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/31438bb0-400a-4da8-a374-c0440535c37c

mobile 
-
```
### Technical Analysis

This component will be created in  libs/pages/elewa/social-impact

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by munenebrian** [comment]
will be working on this

**Comment by GacheruIan** [comment]
working on this with @Patrick-Njiru

**Comment by pronepoet** [comment]
I am working on this

**Comment by 23po** [comment]
Working on this with @sheilah-ndiema

**Comment by codertinie** [comment]
I am working on this with @doreenlulu
