### ISSUE TITLE
🎨  Create the home page lander

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#4]
#  Create the home page lander
---

#### Note: This issue is dependent on #10, please complete that first.

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a nice home page that captures my attention.
I want a good experience on web and phone

### Description

Design:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/3729474/216270330-385f924e-eb7c-43d9-a839-945f333ff909.png">

<img width="233" alt="image" src="https://user-images.githubusercontent.com/3729474/216270431-c2a58205-1f16-4126-8dca-6843a06e3fc4.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the element.

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 30 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone

**Comment by George-Onyango** [comment]
we are working on this with

**Comment by Patrick-Njiru** [comment]
Working on it with @IanGacheru

**Comment by lilmithi** [comment]
working on this with @royokite

**Comment by littlephillips** [comment]
working on this with @Anna-Ashton and @chegeian

**Comment by timothymureithi** [comment]
Working on this with  @[RajabKarume](https://github.com/RajabKarume)

**Comment by NewtonOmbese** [comment]
working on this @mwanasiti

**Comment by Dcolonel6** [comment]
working on this with @muriithi-ian
