### ISSUE TITLE
Create Venture Labs page Module

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#400]
#  Create Venture Labs page Module
---

#### Note:

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a Venture Labs page that contains elewa brands

### Description

The library hasn't been created yet. Create the lib and setup routing to it.
You'll need to add a routing file "venture-labs.routing.ts"
You'll need to add the main page for this lib "venture-labs-page" (inside a pages folder)
Add a venture labs tab on the header and it's routerLink

Add the elewa-main-page template to the venture-labs-page

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81
```

### Technical Analysis

This module will be created in  libs/pages/elewa/venture-labs

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by kahoragachau** [comment]
Working on this
