### ISSUE TITLE
🎨 Create venture labs page top banner

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#401]
#  Create venture labs page top banner
---

#### Note: this issue is dependent on #10 and #400, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a top banner page for the venture-labs page

### Description

As seen on the designs (link below), the section is similar to the page banner component created on #10, reuse that component and pass the relevant data for this section;

The page banner section needs to appear as shown below (link to icons below)

![Screenshot 2023-03-06 at 09 00 40](https://user-images.githubusercontent.com/29625264/223030893-9e0df295-a049-44ec-b966-605105028a33.png)

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81
```

#### Image Url

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690293/elewa-group-website/hero-Images/Venture_labs_y4tnjx.jpg

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-labs

The component will be called venture-labs-hero

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by timothymureithi** [comment]
working on this

**Comment by AshleyN2** [comment]
Hi @IanOdhiambo9 , kindly review.
