### ISSUE TITLE
🎨 Create venture labs info section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#402]
#  Create venture labs info section
---

#### Note: this issue is dependent on #400, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want an info section for the venture-labs page

### Description

The info section contains a number of paragraphs with some info text

The section needs to appear as shown below (link to icons below)

![Screenshot 2023-03-06 at 09 02 48](https://user-images.githubusercontent.com/29625264/223031392-244e44c9-4eec-46de-b9d8-ae6c83cccf06.png)

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81
```

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-labs

The component will be called venture-labs-info

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by Michael-Otieno** [comment]
Worked on this

**Comment by AshleyN2** [comment]
@IanOdhiambo9 , kindly review.
