### ISSUE TITLE
🎨  Create venture labs startups section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#403]
#  Create venture labs startups section
---

#### Note: this issue is dependent on #400, please complete that issue first

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a startups section for the venture-labs page

### Description

The startups section contains the various ways startups are engaged with Elewa.

The section needs to appear as shown below (link to icons below)

![Screenshot 2023-03-06 at 09 07 31](https://user-images.githubusercontent.com/29625264/223031801-8811f8d2-cf29-417b-97e9-fa5ac2cdcd34.png)

Please take note of all the design features

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81
```

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-labs

The component will be called venture-labs-startups

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by McRonaah** [comment]
[Awadh](https://github.com/order6677) working on this

**Comment by chegeian** [comment]
working on this with @Anna-Ashton

**Comment by RajabKarume** [comment]
I'm working on this

**Comment by Tmureithi** [comment]
working on this

**Comment by timothymureithi** [comment]
working on this

**Comment by Michael-Otieno** [comment]
Waiting for review

**Comment by Anna-Ashton** [comment]
kindly review @IanOdhiambo9  the above pr
