### ISSUE TITLE
🎨  Create venture labs page discover

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#405]
#  Create venture labs page discover
---

#### Note: This issue reuses the call-to-action-banner in banners module

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a call to action on the venture labs page.

### Description

Reuse the call-to-action banner

The banner needs to appear as shown below

![Screenshot 2023-03-06 at 09 14 14](https://user-images.githubusercontent.com/29625264/223032960-053fd87d-b6df-4d37-a8d9-123016b5a625.png)

Please take note of all the design features

#### Link to full design:

```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/61b7d771-3f15-4874-a64c-86a1eba37d81/
```

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-labs

The component will be called venture-labs-discover

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by nziokikevin** [comment]
working on this.

**Comment by timothymureithi** [comment]
Working on this
