### ISSUE TITLE
Create venture detail page founders

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#410]
#  Create venture detail page founders
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a founders section on the venture detail page.

### Description

The section needs to appear as shown below

![Screenshot 2023-03-06 at 09 51 48](https://user-images.githubusercontent.com/29625264/223039307-8eb241ea-0b4d-4722-bc56-01417415b6db.png)

Please take note of all the design features

#### Link to full design:

```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/6a994cc0-5cf0-4d13-919e-3953e3b5b9f2
```

### Technical Analysis

This component will be created in  libs/pages/elewa/venture-lab-detail

The component will be called venture-detail-founders

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by omaomach** [comment]
I'll be working on this
