### ISSUE TITLE
🎨 Create venture detail article carousel

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#412]
#  🎨 Create venture detail article carousel
---

####Note: This issue is dependent on #411 

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a component I can reuse to display a horizontal list of articles/news/ etc
.

### Description

Reuse #411 for this issue

![Screenshot 2023-03-06 at 09 52 15](https://user-images.githubusercontent.com/29625264/223041145-9420d693-4a95-4efd-8def-45f75d52b628.png)

Your assignment is to implement the component to appear as above

Please take note of all the design features (including mobile)

#### Link to full design:
```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/6a994cc0-5cf0-4d13-919e-3953e3b5b9f2

mobile 
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/4868ee5e-92ef-479e-bf0d-fbd61dc2f35e
-

```
### Technical Analysis

This component will be created in libs/features/components/ui-lists

The component will be called elewa-group-article-list

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
6. The component is clean and does not have more than 50 lines
7. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
8. The code is isolated to the libs/page/home package, unless a justified reason is specified.
9. The component is aligned using CSS flex
10. The design is responsive for screen, tablet and phone
11. The image renders fast and has multiple srcsets

**Comment by Bel-94** [comment]
Hi @IanOdhiambo9. Kindly provide images for this issue

**Comment by pronepoet** [comment]
I am currently working on this

**Comment by pronepoet** [comment]
Currently working on ths

**Comment by codertinie** [comment]
I am working on this with @doreenlulu
