### ISSUE TITLE
Create News Detail Related articles section

### ISSUE THREAD

**Issue by IanOdhiambo9** [italanta/elewa-group#445]
#  Create News Detail Related articles section
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want to know which articles are related to what I'm currently viewing

### Description

The section needs to appear as shown below

<img width="1284" alt="Screenshot 2023-03-09 at 09 55 04" src="https://user-images.githubusercontent.com/29625264/223944024-3907a8ac-9d7b-4a67-9e81-e0b3e4a039e0.png">

Please take note of all the design features

#### Link to full design:

```
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/9e733abb-3f39-4a84-90f8-2971c92804e8
```

### Technical Analysis

This component will be created in  libs/pages/elewa/news-detail

The component will be called news-related-articles

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by pronepoet** [comment]
Working on this

**Comment by RajabKarume** [comment]
I'm working on this.

**Comment by timothymureithi** [comment]
Working on this issue

**Comment by pronepoet** [comment]
Create a pull request for issue 445
[[#445](Create News Detail Related articles section #445)](https://github.com/italanta/elewa-group/pull/453#issue-1617126405)

**Comment by pronepoet** [comment]
Create News Detail Related articles section
[#445](https://github.com/italanta/elewa-group/pull/453#issue-1617126405)

**Comment by codertinie** [comment]
working on this with @doreenlulu
