### ISSUE TITLE
🎨 Home page - Hero section

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#6]
#  Create the home hero section
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a clear hero section that captures my attention and explains the values of Elewa.
I want a good experience on web and phone

### Description

Design:

<img width="954" alt="image" src="https://user-images.githubusercontent.com/3729474/216347227-0f43ad2a-cae6-4f5c-8123-a38cdc823c73.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/3729474/216347397-23e4e01a-33fc-4eed-9a23-bdc5f1c37f1b.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the element.

In this phase, DO NOT YET ADD THE DROPOUT SECTIONS AS SEEN ON THE RESPONSIVE PAGE (the tabbed titles like "levelling the playing field", ...). Instead, ensure a clean design of the sections when scaling the screen up and down.

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone

**Comment by Allan-Ngugi** [comment]
We are working on this Allan Ngugi and Jeff Odhiambo.

**Comment by jobkarani** [comment]
I am working on this.
