### ISSUE TITLE
🎨 Reusable card component

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#7]
#  A reusable card component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a developer, I want a reusable card component I can use to clearly present data 
I want a good experience on web and phone

### Description

Design:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/3729474/216349771-f8bb9169-c0b6-4bfa-a828-6b2cd4504d89.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

### Technical Analysis

The card component should be placed in the library **libs/features/components/cards**
Use the command `nx generate @nrwl/angular:library features/components/cards` to create this library. Make sure it's a separate commit.

The card is a reusable component that can be used by e.g. the home page to properly display certain components.
The component name is elewa-group-card

The card exposes three Angular inputs of type text, i.e. "title", "subtitle", "imgSrc" and "description".

<img width="358" alt="image" src="https://user-images.githubusercontent.com/3729474/216351672-092cf9a5-78f8-4207-a8a9-6412102f89a3.png">

The module is named "CardsModule" 
It exports the elewa-group-card component, for other modules to import

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone
- [ ] A separate commit is used for each small change
- [ ] The commits and PR are well formatted/use proper documentation
- [ ] The module exports the component

**Comment by KeithWesley254** [comment]
I am working on this

**Comment by Michael-Otieno** [comment]
We are working on this with Festo.

**Comment by pauleen123** [comment]
i am working on this

**Comment by Bel-94** [comment]
I am working on this

**Comment by KeithWesley254** [comment]
@jrosseel @IanOdhiambo9 awaiting your review of my pull request

**Comment by jobkarani** [comment]
We are working on this @DMacharia

**Comment by imaculate-echesa** [comment]
We are working on this @nicco99
