### ISSUE TITLE
🎨 Home page - Activity section

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#8]
#  Create the home "Activity" section
---
**This card depends on:**
- [x] #7 
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows an overview of all the Elewa company branches
I want a good experience on web and phone

### Description

Design:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/3729474/216368080-87e396c8-02e6-4956-841b-a99715ccfe13.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

#### Image links 

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/technolagy_sgfgo6.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690300/elewa-group-website/Icons/PNG/Education_hstyzo.png

https://res.cloudinary.com/dyl3rncv3/image/upload/v1675690296/elewa-group-website/Icons/SVG/venturelabs_icon_vfnmpj.svg

### Technical Analysis

This feature can be found in libs/pages/home
This feature should be a stand alone component. The page should be different from the element.

Re-use components as much as possible
For the three cards (Elewa, iTalanta, Ventures)

### Acceptance Criteria

- [ ] When rendered the component is pixel perfect compared to the design above.
- [ ] The component is clean and does not have more than 50 lines
- [ ] The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
- [ ] The code is isolated to the libs/page/home package, unless a justified reason is specified.
- [ ] The component is aligned using CSS flex
- [ ] The design is responsive for screen, tablet and phone

**Comment by marcokumu** [comment]
I'm working on this component with @mwanjiku56

**Comment by init-commit** [comment]
Working on this issue with @Jane-Wandia.

**Comment by OswaldCc** [comment]
working on this

**Comment by pauleen123** [comment]
i am working on this
