### ISSUE TITLE
🎨 Team & Partners image component

### ISSUE THREAD

**Issue by jrosseel** [italanta/elewa-group#9]
#  Team & Partners image component
---

Quick links: [Summary](#summary) | [Description](#description) | [Technical-Analysis](#Technical-Analysis) | [Acceptance-Criteria](#Acceptance-Criteria)

---

### Summary

As a user I want a section that shows the team and partners
I want a good experience on web and phone

### Description

Design:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/3729474/216369781-7c5a5889-6787-4673-b836-39c6f0d91738.png">

Link to full design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/63e63506-4ea3-4d02-af28-f7cf148b47d9

Responsive design:
https://xd.adobe.com/view/7b72572b-b40a-4618-bfa6-5500ab28f13b-2e21/screen/97e91d3f-d00a-4006-a192-02b0810be1ab

### Technical Analysis

This feature can be found in libs/pages/elewa/home
This feature should be a stand alone component. The page should be different from the element.

The component will be called team-and-partners

Re-use components as much as possible
For the three cards (Elewa, iTalanta, Ventures), use the `<elewa-group-card></elewa-group-card> component.

The image needs to be optimised for web rendering. A low-res version needs to render fast and the high-res can be downloaded in the background.

Use NgOptimizedImage and srcsets - https://angular.io/guide/image-directive

### Acceptance Criteria

1. When rendered the component is pixel perfect compared to the design above.
2. The component is clean and does not have more than 50 lines
3. The component SCSS uses CSS variables for colour, font, ... Connected to the main style.scss
4. The code is isolated to the libs/page/home package, unless a justified reason is specified.
5. The component is aligned using CSS flex
6. The design is responsive for screen, tablet and phone
7. The image renders fast and has multiple srcsets

**Comment by kangzy-fix** [comment]
I will be working on Team & Partners image component.

**Comment by lilmithi** [comment]
I am working on this with [@royokite](https://github.com/royokite)

**Comment by pronepoet** [comment]
I will be working on this

**Comment by SirJimKe** [comment]
I will be working on this

**Comment by kimuit** [comment]
Working on it

**Comment by IanOdhiambo9** [comment]
srcssets is not a required feature of this issue anymore hence reducing the complexity of the challenge.
